services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    environment:
      # Configuração para o Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Configuração para o PostgreSQL
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=transactions_db
      - POSTGRES_USER=transactions_user
      - POSTGRES_PASSWORD=transactions_pass
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: transactions_db
      POSTGRES_USER: transactions_user
      POSTGRES_PASSWORD: transactions_pass
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
