ktor {
    deployment {
        port = 8080
        host = "0.0.0.0"
        watch = [ "dev.emanuelmt" ]
    }
    application {
        modules = [ dev.emanuelmt.ApplicationKt.module ]
    }
    database {
        host = ${?POSTGRES_HOST}
        port = ${?POSTGRES_PORT}
        name = ${?POSTGRES_DB}
        user = ${?POSTGRES_USER}
        password = ${?POSTGRES_PASSWORD}
    }
    redis {
        host = ${?REDIS_HOST}
        port = ${?REDIS_PORT}
    }
}