ktor {
    deployment {
        port = 8080
        host = "0.0.0.0"

        autoreload = true

        watch = [ "dev.emanuelmt" ]
    }
    application {
        modules = [ dev.emanuelmt.ApplicationKt.module ]
    }
}
